### ISSUE TITLE
DroneWall should be able to filter a list of branches

### ISSUE THREAD

**Issue by cantidio** [drone/drone-wall#18]
Right wall, drone wall shows the build status of all branches built in Drone CI, it would be interesting if we could filter the branches we want it to show on the wall, we want all of our branches to be tested, but only master and production to be shown on the wall, for instance:
```
./drone-wall --branches=master,production
```

It would be awesome if it could display the branch name for that commit somewhere in the wall as well.

**Comment by gtaylor** [comment]
Would love to be able to filter entire repos out, as well. May be a separate issue, but figured I'd mention it here.

I have a test fork of our primary repos that I toss experimental builds through. I want it to build and act normally within Drone, but don't want it to show on the dash.

**Comment by Tathanen** [comment]
This should be fairly doable with how v3 of the wall is built.  Can supply a list of branches or repos to include or exclude when building the wall via the command line.  Will see what I can do.

**Comment by gtaylor** [comment]
Awesome! We've got drone-wall up on one of the big TVs in the middle of engineering at Reddit. It's been unexpectedly helpful in getting everyone thinking about tests and CI.

**Comment by Tathanen** [comment]
Closing per 2c0e4db5c6fd53806b4e3411d7d0bc51899cf034.  Can now filter by repo or branch name, and the branch name will appear in the latest builds list when it's anything but `master`.

And with that, `v3.1.0` is ready to ship.  Will have it up in the next few minutes with some notes.
