### ISSUE TITLE
Drone wall crash, undefined: 0

### ISSUE THREAD

**Issue by epipho** [drone/drone-wall#25]
At 12:01:01 the following error shows up in the log and drone-wall exits

```
Nov 18 12:01:01 core-01 sh[867]: undefined:0
Nov 18 12:01:01 core-01 sh[867]: ^
Nov 18 12:01:01 core-01 sh[867]: SyntaxError: Unexpected end of input
Nov 18 12:01:01 core-01 sh[867]: at Object.parse (native)
Nov 18 12:01:01 core-01 sh[867]: at IncomingMessage.<anonymous> (/webapp_root/server.js:45:29)
Nov 18 12:01:01 core-01 sh[867]: at IncomingMessage.emit (events.js:117:20)
Nov 18 12:01:01 core-01 sh[867]: at _stream_readable.js:943:16
Nov 18 12:01:01 core-01 sh[867]: at process._tickCallback (node.js:419:13)
```

No other log entries surrounding the crash and restarting the process made everything happy again.

**Comment by scottferg** [comment]
I think this might be a case of the the official node container having some old bugs that have since been fixed. Testing it now to verify. I did verify that @oren 's solution works well if you want to run it outside of a container.

**Comment by Tathanen** [comment]
This should be "fixed" insomuch as not much of this old config is even present in the current version.  There's an issue (https://github.com/drone/drone-wall/issues/32) for a new dockerfile, let us know if that config, when implemented, exhibits any similar issue.  Closing for now.
