### ISSUE TITLE
Could not retrieve Drone status.

### ISSUE THREAD

**Issue by mastertinner** [drone/drone-wall#36]
I'm getting "Could not retrieve Drone status.". when accessing drone-wall. Before I entered the API root path and the token. If I enter the Drone root path (https://ci.berndsgn.ch/api/) into the browser and append "user/feed", it returns a JSON object so it should be valid and working... I'm using drone-wall as a docker image and Drone from the Rancher catalog in version `0.4-rancher2`.

**Comment by Tathanen** [comment]
Your API path doesn't work for me, is it possible it's only accessible via certain machines or networks, and not where you have the Drone Wall installed?

**Comment by mastertinner** [comment]
Sorry for the confusion, @Tathanen. I deleted that drone instance in the mean time. That's why it's not reachable anymore. It was however running on the same host as the drone-wall instance. Right now I have one running at https://ci.zeilenwerk.ch/.

**Comment by Tathanen** [comment]
Could you look in your browser debug console, in the Network tab, and tell me what you're seeing for requests to user/feed?  There should be a fresh one every few seconds.  The "could not retrieve drone status" message comes when the request receives a 4XX/5XX HTTP response.

**Comment by mastertinner** [comment]
Good idea. It seems to be a CORS issue since the browser's console logs `XMLHttpRequest cannot load https://ci.zeilenwerk.ch/api/user/feed. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://46.101.201.153:3001' is therefore not allowed access.`

**Comment by Tathanen** [comment]
Ah, yeah looks like the OPTIONS request fails on CORS then.  Not much I can do about that from my end, @bradrydzewski any idea why a drone install might be putting up a CORS fuss for the wall?

**Comment by bradrydzewski** [comment]
drone adds `Access-Control-Allow-Origin: *` to all requests by default as well as a few other headers. In fact I believe we resolved a similar error back in February before the new version of the wall was launched https://github.com/drone/drone-wall/issues/30#issuecomment-180562166

so if I had to hypothesize why this error is occurring it would be:

* someone is using an old version of drone from January?
* a reverse proxy server is stripping or overriding environment variables
* bleeding edge browser security policy changes that haven't been accounted for in the drone code

the question I have is why isn't everyone getting this error? either everyone should be getting it, or nobody should be getting it.

**Comment by Tathanen** [comment]
Thanks @bradrydzewski.  @mastertinner I'm not super familiar with Rancher, could you find out if it's installing an older version of Drone?  One from before this issue was resolved earlier this year?

**Comment by mastertinner** [comment]
The version of Drone in the Rancher catalog seems to be pretty outdated indeed... Thanks for your help guys, I'll try to get that updated or use the official Drone image instead.

**Comment by Bothees** [comment]
Hi, am running latest Drone server and runner docker on my local Mac machine and tried to setup drone-wall.

Drone server & runner working as expected, picking up the build and running. when I connect to the Drone-wall, I am getting "Could not retrieve Drone status" and when I look at the Network tab 
I can see 404 error code for /api/user/feed request. Can someone help me what am I missing here?


<img width="1440" alt="Screenshot 2020-09-07 at 12 47 54" src="https://user-images.githubusercontent.com/8228656/92384666-62edb780-f108-11ea-8023-7b845ccd3eab.png">

**Comment by tboerger** [comment]
This never had been updated to recent drone versions.

**Comment by Bothees** [comment]
Hi Thomas, Thank you so much for the answer. I am trying to setup Build Monitor for my repo,

What are the options available if Drone-wall is not updated for the recent versions ?

Are there any Plugins available ?

Please help me with setting up the Dashboard. Thanks.

**Comment by tboerger** [comment]
I don't know about any tool like this wall.

**Comment by Bothees** [comment]
No Problem Tom. what I should do to bring up the Drone-wall for the latest version of Drone?

**Comment by tboerger** [comment]
The API Endpoints got to be updated, maybe you could also simply start using https://github.com/drone/drone-node which gets published as an NPM package.

**Comment by Bothees** [comment]
Hi Tom, Sorry to bother you again. So I just want to double check,

use this drone-node to pull the data from drone-server and display it on the wall right? Sorry if my my questions are silly.

Is there any UI component where I can reuse with drone-node?  Thanks

**Comment by tboerger** [comment]
drone-node does not provide any UI component. You are right, you can use drone-node to fetch the relevant data from any Drone server.

**Comment by Bothees** [comment]
Perfect Thanks Tom. I Just don't want to re-invent the wheel, By any chance do you know anyone been using Drone-node to fetch the data and display it on a dashboard. If you could let me know I can contact and get the details. 

Thank you so much for all the replies.

**Comment by Bothees** [comment]
Hi Tom, I managed the use Drone-node and pulled the data to display on the wall. I just had one question to double check,

It used to be the end-point,

/api/user/feed

is it the equivalent in the latest is,

/api/user/builds

Thanks,
Bothi
