### ISSUE TITLE
Repo list CSS layout issues

### ISSUE THREAD

**Issue by gtaylor** [drone/drone-wall#37]
We're seeing some strange behavior with our repo list and their respective recent build history:
![image](https://cloud.githubusercontent.com/assets/75556/15980754/a3eb6112-2f22-11e6-99fd-1205d64e5998.png)
For the first line, I'd expect to be able to see the repo name. If we showed a few less recent builds, we'd be good for this particular repo (though longer named stuff wouldn't).

The second line seems to have wrapped all the way around.

This is being rendered on recent Chrome for Mac on a TV at 1080p. I'm lazy enough to just run this through `npm start` and point it at localhost:3000, if that matters.

**Comment by Tathanen** [comment]
Yeah, I feel like the solution here is putting a hard limit on the number of PRs displayed, but I'm not sure what the appropriate limit is.  In our usage we never really have more than three open PRs on any repo at a time, usually just one or two.  For shops where you have five+ regularly, the design starts to crumble fundamentally.  It may make sense to order the PRs by most recent activity, and cap at three or four.

I'd be interested to hear what people think about this one.

**Comment by gtaylor** [comment]
We've got a pretty silly amount of PRs open at any given time (40+ at the very least), but our workflow is also fork + PR based. Smaller orgs often just do branches in the canonical repo.

I think limiting this to four and seeing how things goes would be a safe first step.

**Comment by Tathanen** [comment]
Closed per 56e05a0314564b836aa623561a56aada763d62d6, the number of visible PRs is now customizable via the config screen.  Will be included in upcoming `v3.1.0` release.
