### ISSUE TITLE
Restarted builds don't show in the left side activity feed

### ISSUE THREAD

**Issue by gtaylor** [drone/drone-wall#41]
The repo build indicator seems to spin, but the entry in the left menu (if it is still visible) doesn't reflect the restarted build. I would expect to see it hilighted like a normal build.

**Comment by Tathanen** [comment]
Hm I feel like this used to work with Drone 0.3, will look into it.

**Comment by Tathanen** [comment]
Just tried this out, went into the drone interface, clicked restart on a recent build.  It started spinning again in the left pane, turned blue, etc.  What's your usecase, are you also clicking restart via the drone interface?

**Comment by gtaylor** [comment]
I'm clicking restart via the Drone interface. So far I tend to only do this with failed builds, which may or may not be relevant.

As another test, we've currently got five repos activated, but only two have builds in the last week (so we see two up on drone-wall, as we'd expect). If I go to one of the "stale" repos and rebuild the last successful build, I don't see it under the "Latest Builds" list, or the "Watching repos since <X>" listings.

Potentially related?

**Comment by gtaylor** [comment]
This looks to have started working. It may have been something on our end.
