### ISSUE TITLE
Compatibility with Drone 1.0

### ISSUE THREAD

**Issue by maximelebastard** [drone/drone-wall#58]
Hello,

we upgraded our drone server from the 0.8 version to the latest one.

We since get an error on drone-wall

```
Could not retrieve Drone status.
```

This is probably due to a 404 Not Found error on the endpoint

```
GET https://drone.company.io/api/user/feed
```

Is it something easy to upgrade - or does it means a full revamp of this drone-wall app to be compatible with the latest version of drone ?

**Comment by CMorton737** [comment]
Curious about this as well

**Comment by bradrydzewski** [comment]
I believe `/api/user/feed` was changed to `/api/user/builds`

@Tathanen do you have plans to continue maintaining and upgrading this, or should we consider transferring ownership? I am thinking this project should be moved out of the Drone organization since it is really a third party project and I want to avoid confusion about ownership.

**Comment by Tathanen** [comment]
In our organization we're still on Drone v4 and don't plan to upgrade in the immediate future, so yea we haven't had the opportunity to ensure compatibility beyond that.  I'm certainly open to a PR from someone using a later version of Drone who wants to put in a version check that toggles between those two API routes, if that's the only breaking change.  I've expressed concern in the past that some changes to Drone might break the wall more fundamentally (ex. https://github.com/drone/drone/issues/1784), however, and I can't guarantee that some of those haven't happened in later versions, so it may be a bit more complicated than just toggling API routes.

@bradrydzewski agreed, re: this being a third-party project with different expectations.  If you'd like to transfer ownership from `drone` to `vokal` I'd be alright with that.

**Comment by maximelebastard** [comment]
I’m working on a new version made with React/Redux for the 1.0 api. It’s completed at something like 70%. I’ll try to publish it next week

**Comment by msaizar** [comment]
@maximelebastard Really interested in this replacement, please let me know when it is published so I can take a look and try to contribute

**Comment by maximelebastard** [comment]
Hi @msaizar, I paused the development currently.
I'll push the code when I'm back home, basically the UI only what was remaining - and I waited for feedback on that ticket.

https://github.com/drone/drone-ui/issues/299

PS: BTW it only shows a live view of the latest builds and the status of master for every repos. It's not customizable yet.

**Comment by maximelebastard** [comment]
Here it is, the first steps of a Drone 1.0 compatible Drone Wall
https://github.com/maximelebastard/drone-status

(Not finished at all, yet)

**Comment by maximelebastard** [comment]
Hello,
I finally raised a Pull Request on the node-build-monitor project to make it compatible with drone. It's a well architectured tool, it has plenty of deployment options and the compatibility with drone was quite easy to implement. I think it's a better move to capitalize on that kind of largely used projects instead of maintaining a new one.

Here is the related PR on their project.
https://github.com/marcells/node-build-monitor/pull/185
